runtime: python37

-url: /.*
  script:auto

env_variables:
  DB_USER=user1
  DB_PASS=123456
  DB_NAME=baseballpitchers
  DB_SOCKET_DIR="/cloudsql"
  CLOUD_SQL_CONNECTION_NAME='test-328103:us-east1:baseball'
  SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://user1:123456@127.0.0.1:5432/baseballpitchers?host=/cloudsql/test-328103:us-east1:baseball"
