runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

service_account:  test-328103@appspot.gserviceaccount.com
 
beta_settings:
  cloud_sql_instances: test-328103:us-east1:baseball
 
 
env_variables:
  DB_USER: 'test'
  DB_PASS: '123456'
  DB_NAME: 'baseballpitchers'
  DB_HOST: '/cloudsql/test-328103:us-east1:baseball'


manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
