runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

service_account: servicetest@solid-space-326918.iam.gserviceaccount.com
 
beta_settings:
  cloud_sql_instances: solid-space-326918:us-east1:baseball-pitchers=tcp:5432
  

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
